### ISSUE TITLE
Record processed transactions

### ISSUE THREAD

**Issue by moreal** [planetarium/NineChronicles.Bridge#25]
It should record(store) processed transaction relations. (upstream tx <-> downstream tx)

**Comment by Akamig** [comment]
Out of invalidation, We have several event states when comes to recording transactions in two different views, internally, and externally.

### Local Transaction States Through Lifecycle
- Requested (BridgeSe -> Bridge with memo)
- Processing (Handling Request, Not yet Staged)
- Staging (Bridge -> Memo Staged, Not yet confirmed)
- Confirmed (Success, Failure, Invalid)

### Global (External) Transaction States 
- Synced (Data Matching "1:1" Tx Staged successfully, Bridge -> memo)
  - **This must be idempotent, to prevent duplicated response processing (due to unintended nonce-race condition or whatever)**
- Desynced (Diff occured between two)
  - This doesn't mean bridge faulted, but it must be handled in certain timespan, in order to sustain eventual consistency.
  - Also this can be, and recommended to be cross-checked with bridge instance.
